---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-primula-cloud-issuer
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cert-manager-primula-cloud-secret
    creationPolicy: Owner
    template:
      data:
        apiToken: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare/token
