apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: primula-cloud-staging-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@${SECRET_DOMAIN}
    privateKeySecretRef:
      name: primula-cloud-staging-key
    solvers:
      - dns01:
          cloudflare:
            email: admin@${SECRET_DOMAIN}
            apiTokenSecretRef:
              name: cert-manager-primula-cloud-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
