---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: "Kubernetes"
      cache:
        ttl: 1h
        maxSize: 100
      auth:
        serviceAccountSecretRef:
          name: onepassword-secret
          key: token
          namespace: external-secrets
