apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5SyjmYjpvknjrGu5Qg==,iv:6sXvm58+4Ifp/aXvRJxG7B/zGC9TBn/jpCVpZQZyOog=,tag:FqE/12aQnLmiCb4fFd3U9A==,type:str]
sops:
  age:
    - recipient: age1nmj3zwslhcevxnu20tvg4uflv9ts9a38q0sald3wfvrxcw9lsydqg3sdv7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVVZrYVAvQ0hPdDc4bjRS
        d1AwWUZoTzducTgyRGFEeWJOTlFWajZHUUQ0CnJSb0loYWZBcXZUWkZhZlNuR0hj
        L1hYTCsycGpsQWtLcE9LQ1ZMak5wTUUKLS0tIHpxRlpodnZ3M0d4OVBHbUE5QnRN
        K0ZiQnNHRWNLajRSS0lQemlsSjB4WjAKLfLcP/k9pXgCKxQVMfq1XhrZ2tPm+GVa
        o+31o4huJlEQNNMuuBjp2vgoPfn+xKtU2NTKLg3XcjkvT6HdefWkIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T16:52:14Z"
  mac: ENC[AES256_GCM,data:sJTydVFN43UVi4giUADm8L4me+3YoZMCZbtrv9jNX0pwogtY3sui05FRJaiFWWM9h7wRzX9DmYD21q5Szm3vxQ68NxzVbnGn3RHwTdNmsjE/T5zG2czVffGfKp2t+WuopmS4k5hKB+1AwuFIh2jHmbtF8ZwoQzyNRaegLkz8gNA=,iv:+Spesc1MkiFoZaq8Q1nasdK5NvJzrGXcl/M9EbdTdgc=,tag:ScIR+n+Nw16FR2JRu0LLag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
