apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5SyjmYjpvknjrGu5Qg==,iv:6sXvm58+4Ifp/aXvRJxG7B/zGC9TBn/jpCVpZQZyOog=,tag:FqE/12aQnLmiCb4fFd3U9A==,type:str]
    CNPG_BACKUP_ENDPOINT: ENC[AES256_GCM,data:xut37qHzmxbL/+0Fq3+YqlAh2vZh1A2lau/dm507xA==,iv:G5o2WoLCe33TOzjWgmdTBkzdOuscgWangwUcvPX01Ks=,tag:ZQt1RbbYRCCeAqNing/Vzw==,type:str]
    CNPG_BACKUP_DESTINATION: ENC[AES256_GCM,data:3aPjfcBt7E8nnby4LCrY2UNN+4iahhs8bDjd4vnNSQ==,iv:5/xK2U02RQ+yI3IDxRUWtXMyIw81rEWUPS36PCF/rPg=,tag:lq1djHUTC8pEEE0tZpOUwA==,type:str]
sops:
    age:
        - recipient: age1nmj3zwslhcevxnu20tvg4uflv9ts9a38q0sald3wfvrxcw9lsydqg3sdv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVVZrYVAvQ0hPdDc4bjRS
            d1AwWUZoTzducTgyRGFEeWJOTlFWajZHUUQ0CnJSb0loYWZBcXZUWkZhZlNuR0hj
            L1hYTCsycGpsQWtLcE9LQ1ZMak5wTUUKLS0tIHpxRlpodnZ3M0d4OVBHbUE5QnRN
            K0ZiQnNHRWNLajRSS0lQemlsSjB4WjAKLfLcP/k9pXgCKxQVMfq1XhrZ2tPm+GVa
            o+31o4huJlEQNNMuuBjp2vgoPfn+xKtU2NTKLg3XcjkvT6HdefWkIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T15:30:55Z"
    mac: ENC[AES256_GCM,data:BA/QsMnKJRHcXWk9tEkPNxMrKxEXJgxqAEg+5H9MP4R723e7ZBRmPKViozsi6noQYZiA7U+Ioh9hLW6eZ4UulN5FxUNYqeCTCAZFzNBmImtD209+eepdRYP3FhJhyY3KWuTEPB/are4mkDKqhkmn0N8jLYt7SyRrBJEddzwX2DQ=,iv:Kfvyq9s6RtCnGle0UV0OP+dtmzgjq43W8alTYpkefeI=,tag:tFMiF9OnykTQpBzNehClNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
