---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-secret
    creationPolicy: Owner
  data:
    - secretKey: encryption-key
      remoteRef:
        key: n8n/encryption-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-smtp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-smtp-secret
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: smtp/host
    - secretKey: port
      remoteRef:
        key: smtp/port
    - secretKey: username
      remoteRef:
        key: smtp/username
    - secretKey: password
      remoteRef:
        key: smtp/password
