---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n
spec:
  interval: 1h
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    tag: 2.0.1
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
