---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    template:
      data:
        credentials: |
          {
            "AccountTag": "{{ .accountTag }}",
            "TunnelID": "{{ .tunnelId }}",
            "TunnelSecret": "{{ .tunnelSecret }}"
          }
        cert: |
          -----BEGIN ARGO TUNNEL TOKEN-----
          {{ .tunnelCert }}
          -----END ARGO TUNNEL TOKEN-----
  data:
    - secretKey: accountTag
      remoteRef:
        key: cloudflared/account
    - secretKey: tunnelId
      remoteRef:
        key: cloudflared/id
    - secretKey: tunnelSecret
      remoteRef:
        key: cloudflared/secret
    - secretKey: tunnelCert
      remoteRef:
        key: cloudflared/cert
