---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homarr-secret
    creationPolicy: Owner
  data:
    - secretKey: encryption-key
      remoteRef:
        key: homarr/encryption-key
    - secretKey: oidc-client-id
      remoteRef:
        key: homarr/oidc-client-id
    - secretKey: oidc-client-secret
      remoteRef:
        key: homarr/oidc-client-secret
