---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-external
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: traefik-external-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: traefik/username
    - secretKey: password
      remoteRef:
        key: traefik/password
