---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-db-backup
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homarr-db-backup-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: cubbit/access-key-id
    - secretKey: access-secret-key
      remoteRef:
        key: cubbit/access-secret-key
