---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cert-manager
  maxHistory: 3
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    crds:
      enabled: true
    dns01RecursiveNameservers: 1.1.1.1:53,8.8.8.8:53
    dns01RecursiveNameserversOnly: true
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
