---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
  maxHistory: 3
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    defaultSettings:
      defaultReplicaCount: 2
      createDefaultDiskLabeledNodes: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik-internal
      host: longhorn.${SECRET_DOMAIN}
