---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: authentik/secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-smtp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-smtp-secret
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: smtp/host
    - secretKey: port
      remoteRef:
        key: smtp/port
    - secretKey: username
      remoteRef:
        key: smtp/username
    - secretKey: password
      remoteRef:
        key: smtp/password
