---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2026.5.0
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 1h
  maxHistory: 3
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: traefik-external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - auth.${SECRET_DOMAIN}
        paths:
          - "/"
        pathType: Prefix
        tls:
          - hosts:
              - auth.${SECRET_DOMAIN}
    postgresql:
      enabled: false
    email:
      from: "Authentik <noreply@${SECRET_DOMAIN}>"

  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: secret-key
      targetPath: authentik.secret_key
    - kind: Secret
      name: &smtp-secret authentik-smtp-secret
      valuesKey: host
      targetPath: authentik.email.host
    - kind: Secret
      name: *smtp-secret
      valuesKey: port
      targetPath: authentik.email.port
    - kind: Secret
      name: *smtp-secret
      valuesKey: username
      targetPath: authentik.email.username
    - kind: Secret
      name: *smtp-secret
      valuesKey: password
      targetPath: authentik.email.password
    - kind: Secret
      name: &db-secret authentik-db-app
      valuesKey: host
      targetPath: authentik.postgresql.host
    - kind: Secret
      name: *db-secret
      valuesKey: user
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: *db-secret
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: *db-secret
      valuesKey: dbname
      targetPath: authentik.postgresql.name
