apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: primula-cloud-production
spec:
  secretName: primula-cloud-production-tls
  issuerRef:
    name: primula-cloud-production-issuer
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
