---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: immich/client-id
    - secretKey: client-secret
      remoteRef:
        key: immich/client-secret
    - secretKey: issuer-url
      remoteRef:
        key: immich/issuer-url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-smtp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-smtp-secret
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: smtp/host
    - secretKey: port
      remoteRef:
        key: smtp/port
    - secretKey: username
      remoteRef:
        key: smtp/username
    - secretKey: password
      remoteRef:
        key: smtp/password
