---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-secrets
  values:
    replicaCount: 1
    installCRDs: true
    leaderElect: true
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
