router bgp 65100
  ! Router ID
  bgp router-id 10.10.25.1

  ! No policies needed for eBGP neighbors
  no bgp ebgp-requires-policy

  ! Relax autonomous system path matching for multipath routing
  bgp bestpath as-path multipath-relax

  ! Create peer-group k8s-prod with remote ASN 65101
  neighbor k8s-prod peer-group
  neighbor k8s-prod remote-as 65101

  ! Add controller node IPs as neighbors
  neighbor 10.10.25.21 peer-group k8s-prod
  neighbor 10.10.25.22 peer-group k8s-prod
  neighbor 10.10.25.23 peer-group k8s-prod
exit